name: Echo Pipeline
space_name: Example Space

components:
  - id: source
    name: Source
    type: source

  - id: echo
    name: Echo
    type: transformer
    requirements:
      path: requirements.txt
    transformation:
      path: handler.py
    inputs:
      - source

  - id: sink
    name: Sink
    type: sink
    inputs:
      - echo
space_id: 4df9b56c-1324-4cf6-a634-14d21d8a0282
pipeline_id: 6b96a253-522b-4238-9718-35ec99e8c57e
