pipeline_id: cd70ba8f-967e-418e-a326-51dae2d042f2
name: Simple Pipeline

# Space: cicd-test
space_id: dbc98f33-805e-44ff-a5bd-8ee68052f43d

blocks:
  - id: source
    name: Source
    type: source

  - id: main
    name: Main
    type: transformer
    requirements:
      path: requirements.txt
    transformation:
      path: handler.py
    env_vars:
      - name: TEST_VARIABLE
        value: test value
      - name: TEST_SECRET
        value: test_secret
    inputs:
      - source

  - id: sink
    name: Sink
    type: sink
    inputs:
      - main
