pipeline_id: 99f0687b-9301-4c5e-ae4a-5dbd9861a7cd
name: Simple Pipeline

# Space: cicd-test
space_id: dbc98f33-805e-44ff-a5bd-8ee68052f43d

components:
  - id: source
    name: Source
    type: source

  - id: add_new_fields
    name: Add new fields
    type: transformer
    requirements:
      path: add_new_fields/requirements.txt
    transformation:
      path: add_new_fields/handler.py
    inputs:
      - source

  - id: sink
    name: Sink
    type: sink
    inputs:
      - add_new_fields
