pipeline_id: c676ca82-6b94-426c-bc0b-94f394a37e82
name: Simple Pipeline
space_id: dbc98f33-805e-44ff-a5bd-8ee68052f43d

components:
  - id: source
    name: Source
    type: source

  - id: add_new_fields
    name: Add new fields
    type: transformer
    requirements:
      path: add_new_fields/requirements.txt
    transformation:
      path: add_new_fields/handler.py
    inputs:
      - source

  - id: sink
    name: Sink
    type: sink
    inputs:
      - add_new_fields
