name: Pipeline to delete
space_id: dbc98f33-805e-44ff-a5bd-8ee68052f43d

components:
  - id: source
    name: Source
    type: source

  - id: add_new_fields
    name: Add new fields
    type: transformer
    transformation:
      path: handler.py
    inputs:
      - source

  - id: sink
    name: Sink
    type: sink
    inputs:
      - add_new_fields
